package com.pedrodalben.bigbangeventos.trigger;
public enum ActionType { SEND_MESSAGE, SEND_TITLE, PLAY_SOUND, TELEPORT, EXECUTE_COMMAND, ADD_POINTS, REMOVE_POINTS, COMPLETE_STAGE, COMPLETE_CHECKPOINT, PLAYER_COMPLETE, TEAM_COMPLETE, EVENT_FINISH, ELIMINATE_PLAYER, ENABLE_TRIGGER, DISABLE_TRIGGER, GIVE_ITEM, REMOVE_ITEM }
