package com.pedrodalben.bigbangeventos.trigger;
public enum ConditionType { PLAYER_IS_PARTICIPANT, EVENT_IS_RUNNING, PLAYER_NOT_FINISHED, PLAYER_AT_STAGE, PLAYER_HAS_CHECKPOINT, PLAYER_HAS_ALL_CHECKPOINTS, PLAYER_HAS_ITEM, PLAYER_HAS_PERMISSION, PREVIOUS_TRIGGER_COMPLETED, MAX_USES_NOT_REACHED, COOLDOWN_READY }
