package com.pedrodalben.bigbangeventos.stage;

import com.pedrodalben.bigbangeventos.api.OperationResult;
import com.pedrodalben.bigbangeventos.definition.EventDefinition;
import com.pedrodalben.bigbangeventos.domain.DomainEventBus;
import com.pedrodalben.bigbangeventos.domain.ObjectiveEvents;
import com.pedrodalben.bigbangeventos.objective.ObjectiveService;
import com.pedrodalben.bigbangeventos.session.*;
import java.time.*;
import java.util.*;

public final class StageService {
    private final Clock clock; private final ObjectiveService objectives; private final DomainEventBus events;
    public StageService(Clock clock,ObjectiveService objectives,DomainEventBus events){this.clock=clock;this.objectives=objectives;this.events=events;}
    public synchronized StageTransitionResult activateFirst(EventDefinition def,EventSession s){return def.stages().stream().filter(EventStageDefinition::enabled).min(Comparator.comparingInt(EventStageDefinition::order)).map(st->activateStage(def,s,st.id())).orElse(StageTransitionResult.fail("no_stage","Nenhuma etapa habilitada",null));}
    public synchronized StageTransitionResult activateStage(EventDefinition def,EventSession s,String id){EventStageDefinition st=def.stage(id).orElse(null);if(st==null)return fail("stage_not_found","Etapa não encontrada",null);SessionStageProgress p=s.stageProgress().computeIfAbsent(id,k->new SessionStageProgress(id,StageStatus.AVAILABLE,clock.instant()));if(p.status()==StageStatus.ACTIVE||p.status()==StageStatus.COMPLETED)return StageTransitionResult.ok("Etapa já processada",p);if(p.status()==StageStatus.FAILED||p.status()==StageStatus.SKIPPED)return fail("terminal_state","Etapa está em estado terminal",p);if(s.activeStageId().isPresent()&&!s.activeStageId().get().equals(id))return fail("stage_locked","Outra etapa está ativa",p);Instant deadline=st.timeLimitSeconds()==0?null:clock.instant().plusSeconds(st.timeLimitSeconds());p.activate(clock.instant(),deadline);events.publish(new ObjectiveEvents.StageActivated(def.id(),s.id(),p));for(var o:def.objectives())if(o.stageId().equals(id)&&o.enabled()){if(o.scope()==com.pedrodalben.bigbangeventos.objective.ObjectiveScope.PARTICIPANT)for(var participant:s.participants())objectives.activate(def,s,o.id(),participant.playerId(),"stage");else objectives.activate(def,s,o.id(),null,"stage");}return StageTransitionResult.ok("Etapa ativada",p);}
    public synchronized StageTransitionResult completeStage(EventDefinition def,EventSession s,String id){EventStageDefinition st=def.stage(id).orElse(null);SessionStageProgress p=s.stageProgress().get(id);if(st==null)return fail("stage_not_found","Etapa não encontrada",p);if(p==null||p.status()!=StageStatus.ACTIVE)return p!=null&&p.status()==StageStatus.COMPLETED?StageTransitionResult.ok("Etapa já concluída",p):fail("stage_not_active","Etapa não está ativa",p);if(!canAdvance(def,s,id)&&st.required())return fail("objectives_pending","Objetivos obrigatórios pendentes",p);p.complete(clock.instant());events.publish(new ObjectiveEvents.StageCompleted(def.id(),s.id(),p));if(st.nextStageId()!=null&&!st.nextStageId().isBlank())activateStage(def,s,st.nextStageId());return StageTransitionResult.ok("Etapa concluída",p);}
    public synchronized StageTransitionResult failStage(EventDefinition def,EventSession s,String id){SessionStageProgress p=s.stageProgress().get(id);if(p==null)return fail("stage_not_found","Etapa não encontrada",null);if(p.status()==StageStatus.COMPLETED)return StageTransitionResult.ok("Etapa já concluída",p);p.fail(clock.instant());events.publish(new ObjectiveEvents.StageFailed(def.id(),s.id(),p));return StageTransitionResult.ok("Etapa falhou",p);}
    public synchronized StageTransitionResult skipStage(EventDefinition def,EventSession s,String id){SessionStageProgress p=s.stageProgress().get(id);if(p==null)return fail("stage_not_found","Etapa não encontrada",null);if(p.status()==StageStatus.COMPLETED)return StageTransitionResult.ok("Etapa já concluída",p);p.skip(clock.instant());return StageTransitionResult.ok("Etapa ignorada",p);}
    public synchronized Optional<SessionStageProgress> activeStage(EventSession s){return s.activeStageId().flatMap(id->Optional.ofNullable(s.stageProgress().get(id)));}
    public synchronized List<SessionStageProgress> listStages(EventSession s){return List.copyOf(s.stageProgress().values());}
    public synchronized boolean canAdvance(EventDefinition d,EventSession s,String id){if(activeStage(s).map(p->p.stageId().equals(id)).orElse(false)==false)return false;var required=d.objectives().stream().filter(o->o.stageId().equals(id)&&o.required()&&o.enabled()).toList();return s.participants().stream().allMatch(p->required.stream().allMatch(o->objectives.getProgress(s,o.id(),p.playerId()).map(x->x.status()==com.pedrodalben.bigbangeventos.objective.ObjectiveStatus.COMPLETED).orElse(false)));}
    public synchronized StageTransitionResult advance(EventDefinition d,EventSession s){return activeStage(s).map(p->completeStage(d,s,p.stageId())).orElse(fail("no_active_stage","Nenhuma etapa ativa",null));}
    public synchronized void objectiveChanged(EventDefinition d,EventSession s,String stageId){EventStageDefinition st=d.stage(stageId).orElse(null);if(st!=null&&st.autoCompleteWhenObjectivesComplete()&&canAdvance(d,s,stageId))completeStage(d,s,stageId);}
    public synchronized void onTick(Collection<SessionContext> sessions){Instant now=clock.instant();for(SessionContext c:sessions){activeStage(c.session()).ifPresent(p->{if(p.deadline()!=null&&!p.deadline().isAfter(now))failStage(c.definition(),c.session(),p.stageId());});}}
    public record SessionContext(EventDefinition definition,EventSession session){}
    private static StageTransitionResult fail(String c,String m,SessionStageProgress p){return StageTransitionResult.fail(c,m,p);}
}
