package br.com.bigbangcraft.eventos.treasurehunt;

import br.com.bigbangcraft.eventos.treasurehunt.data.TreasureHuntDataKeys;
import br.com.bigbangcraft.eventos.treasurehunt.model.*;
import com.pedrodalben.bigbangeventos.api.BigBangEventosApi;
import com.pedrodalben.bigbangeventos.api.OperationResult;
import com.pedrodalben.bigbangeventos.api.module.EventModuleLogger;
import com.pedrodalben.bigbangeventos.domain.DomainEventBus;
import com.pedrodalben.bigbangeventos.domain.ObjectiveEvents;
import com.pedrodalben.bigbangeventos.definition.EventDefinition;
import com.pedrodalben.bigbangeventos.objective.ObjectiveProgress;
import com.pedrodalben.bigbangeventos.participant.EventParticipant;
import com.pedrodalben.bigbangeventos.platform.PlatformPlayerService;
import com.pedrodalben.bigbangeventos.session.EventSession;
import java.util.*;

public final class TreasureHuntSessionService {
    private final BigBangEventosApi api; private final PlatformPlayerService players; private final EventModuleLogger logger; private final List<AutoCloseable> subscriptions=new ArrayList<>();
    public TreasureHuntSessionService(BigBangEventosApi api,PlatformPlayerService players,EventModuleLogger logger,DomainEventBus events){this.api=api;this.players=players;this.logger=logger;subscriptions.add(events.subscribe("treasure_hunt",ObjectiveEvents.ObjectiveCompleted.class,this::objectiveCompleted));subscriptions.add(events.subscribe("treasure_hunt",ObjectiveEvents.StageCompleted.class,this::stageCompleted));subscriptions.add(events.subscribe("treasure_hunt",ObjectiveEvents.ParticipantCompleted.class,this::participantCompleted));}
    public void start(EventSession s){EventDefinition d=api.findEvent(s.eventId()).orElse(null);if(d==null)return;api.stageService().activateFirst(d,s);s.participants().forEach(p->showCurrent(d,s,p));logger.info("Treasure Hunt iniciado para {}",s.eventId());}
    public void finish(EventSession s){s.participants().forEach(p->{if(players.isOnline(p.playerId()))players.sendMessage(p.playerId(),ranking(s));});}
    public void cancel(EventSession s,String reason){s.participants().forEach(p->{if(players.isOnline(p.playerId()))players.sendMessage(p.playerId(),"§cCaça ao Tesouro cancelada: "+reason);});}
    public void shutdown(){subscriptions.forEach(x->{try{x.close();}catch(Exception ignored){}});subscriptions.clear();}
    public OperationResult clue(UUID player){var s=api.getSessionByPlayer(player).orElse(null);if(s==null)return OperationResult.fail("not_participant","Você não está em evento");var d=api.findEvent(s.eventId()).orElse(null);var p=s.participant(player).orElse(null);if(d==null||p==null)return OperationResult.fail("not_found","Evento não encontrado");showCurrent(d,s,p);return OperationResult.ok("Pista exibida");}
    public String progress(EventSession s,UUID player){var d=api.findEvent(s.eventId()).orElse(null);if(d==null)return "Evento não encontrado";var p=s.participant(player).orElse(null);if(p==null)return "Jogador não participa";String stage=s.activeStageId().orElse("nenhuma");long done=api.objectiveService().listProgress(d,s,player).stream().filter(x->x.status()==com.pedrodalben.bigbangeventos.objective.ObjectiveStatus.COMPLETED).count();return "Etapa: "+stage+" | Objetivos concluídos: "+done+"/"+d.objectives().size()+" | Fragmentos: "+p.typedData().getOrDefault(TreasureHuntDataKeys.FRAGMENTS)+" | Pontos: "+p.typedData().getOrDefault(TreasureHuntDataKeys.SCORE);}
    private void objectiveCompleted(ObjectiveEvents.ObjectiveCompleted e){if(!"treasure_hunt".equals(api.findEvent(e.eventId()).map(EventDefinition::type).orElse("")))return;EventSession s=api.getActiveSession(e.eventId()).orElse(null);if(s==null||e.progress().playerId()==null)return;var p=s.participant(e.progress().playerId()).orElse(null);if(p==null)return;long points=number(e.progress().metadata().get("points"),0);if(points>0)addScore(p,points);if("true".equalsIgnoreCase(e.progress().metadata().get("fragment")))p.typedData().set(TreasureHuntDataKeys.FRAGMENTS,p.typedData().getOrDefault(TreasureHuntDataKeys.FRAGMENTS)+1);EventDefinition d=api.findEvent(e.eventId()).orElse(null);if(d!=null&&allRequired(d,s,p.playerId()))api.completeParticipant(e.eventId(),p.playerId(),"MANUAL_FINISH");}
    private void stageCompleted(ObjectiveEvents.StageCompleted e){EventSession s=api.getActiveSession(e.eventId()).orElse(null);EventDefinition d=api.findEvent(e.eventId()).orElse(null);if(s==null||d==null)return;for(var p:s.participants()){var done=p.typedData().getOrDefault(TreasureHuntDataKeys.COMPLETED_STAGES);if(done.contains(e.progress().stageId()))continue;var next=new HashSet<>(done);next.add(e.progress().stageId());p.typedData().set(TreasureHuntDataKeys.COMPLETED_STAGES,next);long points=number(d.stage(e.progress().stageId()).map(x->x.metadata().get("points")).orElse(null),0);if(points>0)addScore(p,points);showCurrent(d,s,p);}}
    private void participantCompleted(ObjectiveEvents.ParticipantCompleted e){EventSession s=api.getActiveSession(e.eventId()).orElse(null);if(s==null)return;var p=s.participant(e.playerId()).orElse(null);if(p==null)return;if(!p.typedData().getOrDefault(TreasureHuntDataKeys.COMPLETION_REWARDED)){p.typedData().set(TreasureHuntDataKeys.COMPLETION_REWARDED,true);addScore(p,100);if(players.isOnline(p.playerId()))players.sendMessage(p.playerId(),"§6Caça ao Tesouro concluída! §e"+p.typedData().getOrDefault(TreasureHuntDataKeys.SCORE)+" pontos");}if(TreasureHuntConfiguration.finishMode(api.findEvent(e.eventId()).orElseThrow())==TreasureHuntFinishMode.FIRST_FINISHER)api.finishEvent(e.eventId());else if(TreasureHuntConfiguration.finishMode(api.findEvent(e.eventId()).orElseThrow())==TreasureHuntFinishMode.ALL_FINISHERS&&s.participants().stream().filter(x->x.state()==com.pedrodalben.bigbangeventos.participant.ParticipantState.ACTIVE).count()==0)api.finishEvent(e.eventId());}
    private boolean allRequired(EventDefinition d,EventSession s,UUID player){return d.objectives().stream().filter(o->o.required()&&o.enabled()).allMatch(o->api.objectiveService().getProgress(s,o.id(),player).map(x->x.status()==com.pedrodalben.bigbangeventos.objective.ObjectiveStatus.COMPLETED).orElse(false));}
    private void showCurrent(EventDefinition d,EventSession s,EventParticipant p){s.activeStageId().flatMap(d::stage).ifPresent(stage->{String title=stage.metadata().getOrDefault("clue-title",stage.displayName());String text=stage.metadata().getOrDefault("clue",stage.description());p.typedData().set(TreasureHuntDataKeys.CURRENT_CLUE,text);var clues=new HashSet<>(p.typedData().getOrDefault(TreasureHuntDataKeys.DISCOVERED_CLUES));clues.add(stage.id());p.typedData().set(TreasureHuntDataKeys.DISCOVERED_CLUES,clues);if(players.isOnline(p.playerId())){players.sendTitle(p.playerId(),title,text);players.sendMessage(p.playerId(),"§e"+text);}});}
    private String ranking(EventSession s){List<EventParticipant> list=new ArrayList<>(s.participants());list.sort(Comparator.comparingLong((EventParticipant p)->-p.typedData().getOrDefault(TreasureHuntDataKeys.SCORE)).thenComparing(p->p.finishedAt().orElse(java.time.Instant.MAX)).thenComparing(EventParticipant::playerId));StringBuilder out=new StringBuilder("§6Ranking Treasure Hunt:");int i=1;for(var p:list)out.append("\n§e").append(i++).append("º ").append(p.knownName()).append(" — ").append(p.typedData().getOrDefault(TreasureHuntDataKeys.SCORE)).append(" pontos");return out.toString();}
    private static void addScore(EventParticipant p,long value){p.typedData().set(TreasureHuntDataKeys.SCORE,p.typedData().getOrDefault(TreasureHuntDataKeys.SCORE)+value);}
    private static long number(String value,long fallback){try{return value==null?fallback:Long.parseLong(value);}catch(NumberFormatException e){return fallback;}}
}
